# Definição da variável baseUrl
@baseUrl = http://127.0.0.1:8080/calanggo/api
@shortCode = mgTCe1f

### Criar uma URL encurtada (POST /shorten)
POST {{baseUrl}}/shorten
Content-Type: application/json

{
  "originalUrl": "https://www.example.com",
  "expiresAt": null
}

### Obter a URL original a partir do shortCode (GET /shorten/{shortCode})
GET {{baseUrl}}/shorten/{{shortCode}}

### Obter estatísticas de uma URL encurtada (GET /shorten/{shortCode}/statistics)
GET {{baseUrl}}/shorten/{{shortCode}}/statistics
